# Generated by Django 2.0.2 on 2018-03-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_ovh_chall',
            field=models.BooleanField(default=False),
        ),
    ]
