# Generated by Django 2.0.2 on 2018-03-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20180306_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='nb_points_override',
            field=models.IntegerField(default=-10),
        ),
    ]
