# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField()),
                ('comes_from', models.CharField(blank=True, max_length=255, null=True)),
                ('wants_to_be_contacted', models.BooleanField(default=False)),
                ('date_last_validation', models.DateTimeField(default=django.utils.timezone.now)),
                ('nb_unread_news', models.PositiveIntegerField(default=0)),
                ('bug_bounty_points', models.PositiveIntegerField(default=0)),
                ('comment_bug_bounty', models.TextField(blank=True, null=True)),
                ('on_site', models.BooleanField(default=False)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
