# Generated by Django 2.0.2 on 2018-03-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_ssh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprofile',
            name='avatar',
            field=models.URLField(default='https://media.giphy.com/media/l46C6sdSa5DVSJnLG/giphy-downsized.gif'),
        ),
    ]
